name: Achievements
favicon: null
layout_spectrum: 0.051415093475952744
typography_spectrum: 0.44876491255126894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
